const exchangeDirectory=[{name:"Binance",provider:"binance"},{name:"Bybit",provider:"bybit"},{name:"Coinbase",provider:"coinbase"},{name:"Kraken",provider:"kraken"},{name:"OKX",provider:"okx"},{name:"KuCoin",provider:"kucoin"},{name:"Bitget",provider:"bitget"},{name:"Gate.io",provider:"gate"},{name:"MEXC",provider:"mexc"},{name:"Crypto.com",provider:"cryptocom"},{name:"Gemini",provider:"gemini"},{name:"Bitstamp",provider:"bitstamp"},{name:"Bitfinex",provider:"bitfinex"},{name:"HTX",provider:"htx"},{name:"Poloniex",provider:"poloniex"},{name:"BitMart",provider:"bitmart"},{name:"LBank",provider:"lbank"},{name:"BingX",provider:"bingx"},{name:"Phemex",provider:"phemex"},{name:"WhiteBIT",provider:"whitebit"},{name:"CoinEx",provider:"coinex"},{name:"XT.COM",provider:"xt"},{name:"Deepcoin",provider:"deepcoin"},{name:"AscendEX",provider:"ascendex"},{name:"Bitrue",provider:"bitrue"},{name:"CoinW",provider:"coinw"},{name:"DigiFinex",provider:"digifinex"},{name:"Toobit",provider:"toobit"},{name:"WEEX",provider:"weex"},{name:"P2PB2B",provider:"p2pb2b"},{name:"Upbit",provider:"upbit"},{name:"Bitflyer",provider:"bitflyer"},{name:"Bithumb",provider:"bithumb"},{name:"Coinone",provider:"coinone"},{name:"Korbit",provider:"korbit"},{name:"BitMEX",provider:"bitmex"},{name:"Deribit",provider:"deribit"},{name:"WOO X",provider:"woo"},{name:"HashKey",provider:"hashkey"},{name:"Bitkub",provider:"bitkub"},{name:"Indodax",provider:"indodax"},{name:"Mercado Bitcoin",provider:"mercado"},{name:"Foxbit",provider:"foxbit"},{name:"Bitso",provider:"bitso"},{name:"Ripio",provider:"ripio"},{name:"Rain",provider:"rain"},{name:"Coincheck",provider:"coincheck"},{name:"Zaif",provider:"zaif"},{name:"Bitbank",provider:"bitbank"},{name:"OKCoin",provider:"okcoin"},{name:"BloFin",provider:"blofin"},{name:"BTSE",provider:"btse"},{name:"Bitunix",provider:"bitunix"},{name:"dYdX",provider:"dydx"},{name:"Coinmetro",provider:"coinmetro"},{name:"CoinZoom",provider:"coinzoom"},{name:"Bit2Me",provider:"bit2me"},{name:"LATOKEN",provider:"latoken"},{name:"Tokocrypto",provider:"tokocrypto"},{name:"CoinSpot",provider:"coinspot"},{name:"Independent Reserve",provider:"independentreserve"},{name:"CEX.IO",provider:"cex"},{name:"Currency.com",provider:"currencycom"},{name:"TimeX",provider:"timex"},{name:"NovaDAX",provider:"novadax"},{name:"Bitexen",provider:"bitexen"},{name:"Icrypex",provider:"icrypex"},{name:"Paribu",provider:"paribu"},{name:"BTCTurk",provider:"btcturk"},{name:"Bitci",provider:"bitci"},{name:"Pionex",provider:"pionex"},{name:"BitTrade",provider:"bittrade"},{name:"Uphold",provider:"uphold"},{name:"BigONE",provider:"bigone"},{name:"Bitvavo",provider:"bitvavo"},{name:"EXMO",provider:"exmo"},{name:"BTC Markets",provider:"btcmarkets"}];
const input=document.getElementById("exchangeDirectorySearch");
const grid=document.getElementById("exchangeDirectoryGrid");
const count=document.getElementById("exchangeDirectoryCount");
function render(list){
 count.textContent=list.length+" exchanges";
 grid.innerHTML=list.length?list.map(e=>'<a class="exchange-directory-card" href="exchange.html?exchange='+encodeURIComponent(e.provider)+'"><img class="exchange-directory-logo" src="https://cdn.simpleicons.org/'+encodeURIComponent(e.provider)+'" alt="" onerror="this.style.visibility=\'hidden\'"><span class="exchange-directory-info"><b>'+e.name+'</b><span>Live analysis • BTC market</span></span><span class="exchange-directory-arrow">↗</span></a>').join(""):'<div class="exchange-directory-empty">No exchange found. Try another name.</div>';
}
render(exchangeDirectory);
input.addEventListener("input",()=>{const q=input.value.trim().toLowerCase();render(exchangeDirectory.filter(e=>e.name.toLowerCase().includes(q)||e.provider.toLowerCase().includes(q)))});
