const API="https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=true&sparkline_duration=7d&price_change_percentage=24h";
const GLOBAL_API="https://api.coingecko.com/api/v3/global";
const globalCap=document.getElementById("globalCap"),globalVolume=document.getElementById("globalVolume"),btcDominance=document.getElementById("btcDominance"),activeCoins=document.getElementById("activeCoins"),topGainers=document.getElementById("topGainers"),topLosers=document.getElementById("topLosers");
const body=document.getElementById("marketTableBody"),search=document.getElementById("marketSearch"),sort=document.getElementById("sortSelect"),more=document.getElementById("loadMore"),status=document.getElementById("marketStatus"),favoritesOnly=document.getElementById("favoritesOnly");
const WATCHLIST_KEY="gugee_watchlist"; let coins=[],visible=50;
const getFavorites=()=>JSON.parse(localStorage.getItem(WATCHLIST_KEY)||"[]");
const saveFavorites=v=>localStorage.setItem(WATCHLIST_KEY,JSON.stringify(v));
const money=v=>v==null?"--":v>=1?v.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}):v.toLocaleString("en-US",{style:"currency",currency:"USD",maximumSignificantDigits:5});
const compact=v=>v==null?"--":new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:2}).format(v);
function render(){
 const q=search.value.trim().toLowerCase();
 let list=coins.filter(c=>(c.name+" "+c.symbol).toLowerCase().includes(q));
 if(favoritesOnly.checked){const favs=getFavorites();list=list.filter(c=>favs.includes(c.id));}
 const s=sort.value;
 list.sort((a,b)=>s==="price_desc"?b.current_price-a.current_price:s==="change_desc"?(b.price_change_percentage_24h||-Infinity)-(a.price_change_percentage_24h||-Infinity):s==="change_asc"?(a.price_change_percentage_24h||Infinity)-(b.price_change_percentage_24h||Infinity):s==="volume_desc"?b.total_volume-a.total_volume:s==="rank_asc"?a.market_cap_rank-b.market_cap_rank:b.market_cap-a.market_cap);
 list=list.slice(0,visible);
 if(!list.length){body.innerHTML='<tr><td colspan="7" class="market-loading">No cryptocurrencies found.</td></tr>';return}
 body.innerHTML=list.map(c=>{const ch=c.price_change_percentage_24h,fav=getFavorites().includes(c.id);return '<tr class="market-row" data-id="'+c.id+'"><td class="rank">'+c.market_cap_rank+'</td><td><div class="asset"><img src="'+c.image+'" alt=""><div><b>'+c.name+'</b><span>'+c.symbol.toUpperCase()+'</span></div></div></td><td><button class="market-favorite '+(fav?"active":"")+'" data-fav="'+c.id+'">'+(fav?"★":"☆")+'</button></td><td class="sparkline-cell"><canvas class="sparkline" data-values=' + "' + JSON.stringify(c.sparkline_in_7d?.price||[]) + '" + '></canvas></td><td><b>'+money(c.current_price)+'</b></td><td class="'+(ch>=0?"positive":"negative")+'">'+(ch>=0?"+":"")+(ch==null?"--":ch.toFixed(2)+"%")+'</td><td>'+money(c.market_cap)+'</td><td>'+compact(c.total_volume)+'</td></tr>'}).join("");
 document.querySelectorAll(".market-row").forEach(r=>r.onclick=e=>{if(e.target.closest(".market-favorite"))return;location.href="crypto.html?coin="+encodeURIComponent(r.dataset.id)});drawSparklines();
 document.querySelectorAll(".market-favorite").forEach(btn=>btn.onclick=e=>{e.stopPropagation();const id=btn.dataset.fav,f=getFavorites(),i=f.indexOf(id);if(i>=0)f.splice(i,1);else f.push(id);saveFavorites(f);render()});
 more.style.display=list.length>=visible&&visible<coins.length?"":"none";
}
function drawSparklines(){document.querySelectorAll(".sparkline").forEach(canvas=>{const v=JSON.parse(canvas.dataset.values||"[]"),ctx=canvas.getContext("2d");canvas.width=110;canvas.height=34;if(v.length<2)return;const min=Math.min(...v),max=Math.max(...v),range=max-min||1;ctx.beginPath();v.forEach((p,i)=>{const x=i/(v.length-1)*110,y=30-(p-min)/range*26;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=v[v.length-1]>=v[0]?"#22c55e":"#ef4444";ctx.lineWidth=1.5;ctx.stroke()})}
function globalMoney(v){return v==null?"--":v.toLocaleString("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:2})}
function highlights(){const valid=coins.filter(c=>Number.isFinite(c.price_change_percentage_24h));const gain=valid.slice().sort((a,b)=>b.price_change_percentage_24h-a.price_change_percentage_24h).slice(0,5);const lose=valid.slice().sort((a,b)=>a.price_change_percentage_24h-b.price_change_percentage_24h).slice(0,5);const item=c=>"<div class=\"highlight-row highlight-link\" data-coin=\""+c.id+"\"><span>"+c.name+"</span><b class=\""+(c.price_change_percentage_24h>=0?"positive":"negative")+"\">"+(c.price_change_percentage_24h>=0?"+":"")+c.price_change_percentage_24h.toFixed(2)+"%</b></div>";topGainers.innerHTML=gain.map(item).join("");topLosers.innerHTML=lose.map(item).join("");document.querySelectorAll(".highlight-link").forEach(row=>row.onclick=()=>location.href="crypto.html?coin="+encodeURIComponent(row.dataset.coin))}
async function loadGlobal(){try{const r=await fetch(GLOBAL_API);if(!r.ok)throw new Error();const d=await r.json();globalCap.textContent=globalMoney(d.data.total_market_cap.usd);globalVolume.textContent=globalMoney(d.data.total_volume.usd);btcDominance.textContent=d.data.market_cap_percentage.btc.toFixed(2)+"%";activeCoins.textContent=d.data.active_cryptocurrencies.toLocaleString()}catch(e){}}
async function load(){try{const r=await fetch(API);if(!r.ok)throw new Error("API failed");coins=await r.json();status.textContent="Live CoinGecko data";render();highlights();loadGlobal()}catch(e){body.innerHTML='<tr><td colspan="7" class="market-loading">Market data could not be loaded. Try again.</td></tr>';status.textContent="Data unavailable"}}
search.addEventListener("input",()=>{visible=50;render()});favoritesOnly.addEventListener("change",()=>{visible=50;render()});sort.addEventListener("change",render);more.addEventListener("click",()=>{visible+=50;render()});load();loadGlobal();setInterval(load,60000);setInterval(loadGlobal,60000);